version: "3.9"
services:
  db:
    image: postgres
    restart: always
    container_name: pgdatabase
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    ports:
      - '5433:5432'