version: "3.9"
services:
  db:
    image: postgres
    restart: always
    container_name: pgdatabase-test
    environment:
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_USER=prisma
      - POSTGRES_DB=test
    ports:
      - '5433:5432'