version: "3.9"
services:
  db:
    image: postgres
    restart: always
    container_name: pgdatabase
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dev
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

volumes:
  pgdata:
    external: true