PUT http://localhost:5000/api/v1/assistances/1/students
Cookie: user_auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0OTQzOTkyOSwiZXhwIjoxNjQ5NDQwNTI5fQ.uXRXUoflNZB-KjU-Kg1pgK58KdAHdSU_G9TUFVzmK_k
Content-Type: application/json

{
  "description": "Que tall",
  "assistances": [
    {
      "student_id": 1,
      "attended": false
    }
  ]
}