PUT http://localhost:5000/api/v1/assignments/1
Cookie: user_auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0OTE4NTY5OSwiZXhwIjoxNjQ5MTg2Mjk5fQ.uSsXURFFpwoNPiOWZU8YhiE9Rx96qpMFnPWbqIJaTjA
Content-Type: application/json

{
  "title": "ESTO ES UNA PRIMERA ASIGNACIÓN"
}

###

POST http://localhost:5000/api/v1/assignments/1/scores
Cookie: user_auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0OTcyMTcxMiwiZXhwIjoxNjQ5NzIyMzEyfQ.nv9agV1smd130YAp_VT8AWVMhoJdJjDt-tzBgJtt5FY
Content-Type: application/json

[
  {
    "student_id": 1,
    "value": 1,
    "commentary": "probando"
  }
]

###
GET http://localhost:5000/api/v1/assignments/1/scores
Cookie: user_auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0OTcyNjc3MywiZXhwIjoxNjQ5NzI3MzczfQ.UAyAl6q0Zlzx_1ArsH6ORAfTI-ixS638J3VIxSCyzhg

###

PUT http://localhost:5000/api/v1/assignments/1/qualify
Cookie: user_auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0OTI4NDk2NSwiZXhwIjoxNjQ5Mjg1NTY1fQ.euGY4ReqG21Wddz42sft4fMvILPKeFKHX3F6KMsrH9c
Content-Type: application/json

[
  {
    "student_id": 1,
    "value": 1
  }
]

###
DELETE http://localhost:5000/api/v1/assignments/2
Cookie: user_auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0OTY5NDYxMywiZXhwIjoxNjQ5Njk1MjEzfQ.oYXeIZ6eNYOhKgleFi0KzsKw9wwnt0-ANdOW7wMtOwY
