GET http://localhost:5000/api/v1/users/me
Cookie: user_auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0ODQ5NjczMiwiZXhwIjoxNjQ4NDk3MDMyfQ.sdrMBVNsPw0C45sYetzt2Qd3UtF6dI6hxd8F3C5iJAo

###
GET http://localhost:5000/api/v1/users/students
Cookie: user_auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0OTU0MTExMSwiZXhwIjoxNjQ5NTQxNzExfQ.G8hgOinHxUi-s7H88cL1MNRtW_nhJ3wih7BK0Q9eBJE

###

POST http://localhost:5000/api/v1/users/support-email
Cookie: user_auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MDkxMzI4MSwiZXhwIjoxNjUwOTEzODgxfQ.YLgqJPdEhkyXEDgMDFABZsRKSWFDUf3ygd8EHNPq1iE
Content-Type: application/json

{
  "title": "No puedo crear un comunicado",
  "description": "Al momento de presionar el botón de crear comunicado, no me aparece el formulario"
}